version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASS
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    labels:
      - "traefik.enable=false"    
    networks:
      - web

  fast_food:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-fast-food:1.0.0
    container_name: fast_food_container
    networks:
      - web  
    restart: always
    ports:
      - '8724:8080'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fast-food.rule=Host(`fast-food.ambition.io.vn`)"

      - "traefik.http.routers.fast-food.tls=true"
      - "traefik.http.services.fast-food.loadbalancer.server.port=8080"

      - traefik.http.middlewares.fastfood-redirect.redirectregex.regex=^http://www\.(.*)
      - "traefik.http.middlewares.fastfood-redirect.redirectregex.replacement=http://$${1}"
      - "traefik.http.routers.fast-food.middlewares=fastfood-redirect"   

networks:
  web:
    external: true  
