services:
  db:
    image: mysql:8.0
    container_name: server-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASS
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-fast-food
    depends_on:
      - db
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - SECRET_JWT=$SECRET_JWT
    ports:
      - "8081:8080"
    networks:
      - app-network
    
volumes:
  db_data:

networks:
  app-network: