services:
  db:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASS
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-fast-food:1.0
    restart: always
    depends_on:
      - db
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - SECRET_JWT=$SECRET_JWT
    ports:
      - ":8080"
    networks:
      - web
    
volumes:
  db_data:

networks:
  web:
